{ question: "What is the largest mammal in the world?", answers: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], correct: 1 },
{ question: "Which animal is known as the 'ship of the desert'?", answers: ["Camel", "Elephant", "Horse", "Lion"], correct: 0 },
{ question: "What is the fastest land animal?", answers: ["Cheetah", "Lion", "Gazelle", "Pronghorn"], correct: 0 },
{ question: "What do you call a group of crows?", answers: ["Flock", "Herd", "Murder", "Pack"], correct: 2 },
{ question: "What is the largest fish in the ocean?", answers: ["Whale Shark", "Great White Shark", "Blue Whale", "Manta Ray"], correct: 0 },
{ question: "What is the national animal of Australia?", answers: [ "Koala", "Kangaroo", "Emu", "Platypus"], correct: 1 },
{ question: "What type of animal is the largest primate?", answers: ["Gorilla", "Orangutan", "Chimpanzee", "Human"], correct: 3 },
{ question: "What is a female elephant called?", answers: [ "Ewe", "Doe", "Cow", "Sow"], correct: 2 },
{ question: "What is the tallest animal in the world?", answers: ["Giraffe", "Elephant", "Ostrich", "Gorilla"], correct: 0 },
{ question: "What do you call a baby kangaroo?", answers: [ "Calf", "Fawn", "Joey", "Pup"], correct: 2 },
{ question: "Which bird is known for its beautiful tail feathers?", answers: ["Peacock", "Ostrich", "Eagle", "Hawk"], correct: 0 },
{ question: "What is the smallest breed of dog?", answers: [ "Dachshund", "Pomeranian", "Chihuahua", "Yorkshire Terrier"], correct: 2 },
{ question: "What is the fastest bird on foot?", answers: [ "Emu", "Cassowary", "Ostrich", "Rhea"], correct: 2 },
{ question: "What is the largest living species of lizard?", answers: ["Monitor Lizard", "Komodo Dragon", "Gecko", "Iguana"], correct: 1 },
{ question: "What is the only mammal capable of true flight?", answers: [ "Bird", "Butterfly", "Bat", "Pterosaur"], correct: 2 },
{ question: "What is the largest species of bear?", answers: ["Brown Bear", "Black Bear", "Sun Bear", "Polar Bear"], correct: 3 },
{ question: "What is the world's largest land mammal?", answers: ["African Elephant", "Indian Elephant", "White Rhinoceros", "Hippopotamus"], correct: 0 },
{ question: "What is a group of lions called?", answers: ["Pack", "Herd", "Pride", "Gaggle"], correct: 2 },
{ question: "What is the only continent on which giraffes live in the wild?", answers: [ "Asia", "South America", "Australia", "Africa"], correct: 3 },
{ question: "What is the fastest marine animal?", answers: [ "Bluefin Tuna", "Sailfish", "Dolphin", "Marlin"], correct: 1 },
{ question: "Which animal is known for rolling into a ball when threatened?", answers: ["Armadillo", "Porcupine", "Hedgehog", "Tortoise"], correct: 2 },
{ question: "What is the largest bird of prey in the world?", answers: [ "Golden Eagle", "Bald Eagle", "Peregrine Falcon", "Andean Condor"], correct: 3 },
{ question: "What is a baby goat called?", answers: ["Calf", "Kid", "Foal", "Lamb"], correct: 1 },
{ question: "What is the largest species of penguin?", answers: ["King Penguin", "Adelie Penguin", "Gentoo Penguin", "Emperor Penguin"], correct: 3 },
{ question: "Which animal can sleep standing up?", answers: ["Cow", "Goat", "Sheep", "Horse"], correct: 3 },
{ question: "What is the world's longest venomous snake?", answers: ["King Cobra", "Black Mamba", "Taipan", "Rattlesnake"], correct: 0 },
{ question: "What is a baby swan called?", answers: ["Pullet", "Gosling", "Duckling", "Cygnet"], correct: 3 },
{ question: "What is the largest species of living fish?", answers: [ "Great White Shark", "Whale Shark", "Manta Ray", "Tiger Shark"], correct: 1 },
{ question: "What is the largest species of cat?", answers: [ "Lion", "Jaguar", "Leopard", "Tiger"], correct: 3 },
{ question: "What is a female fox called?", answers: [ "Doe", "Vixen","Hen", "Cow"], correct: 1 },
{ question: "What is the fastest land animal over short distances?", answers: ["Cheetah", "Pronghorn", "Springbok", "Hare"], correct: 0 },
{ question: "What is a male deer called?", answers: [ "Doe", "Stag", "Fawn", "Buck"], correct: 3 },
{ question: "What is the smallest species of monkey?", answers: ["Tarsier", "Pygmy Marmoset", "Squirrel Monkey", "Capuchin Monkey"], correct: 1 },
{ question: "What is the world's largest species of crab?", answers: [ "King Crab", "Dungeness Crab", "Blue Crab", "Japanese Spider Crab"], correct: 3 },
{ question: "What is the largest species of kangaroo?", answers: [ "Eastern Grey Kangaroo", "Western Grey Kangaroo", "Red Kangaroo", "Antilopine Kangaroo"], correct: 2 },
{ question: "What is the world's largest species of tortoise?", answers: ["Galapagos Tortoise", "Aldabra Giant Tortoise", "Sulcata Tortoise", "Indian Star Tortoise"], correct: 0 },
{ question: "What is a female horse called?", answers: ["Mare", "Stallion", "Gelding", "Colt"], correct: 0 },