let teams = [];
let scores = {};
let currentQuestionIndex = 0;
let questions = [];
let usedQuestions = [];

function addTeam() {
    const teamName = document.getElementById('teamName').value;
    if (teamName && !teams.includes(teamName)) {
        teams.push(teamName);
        scores[teamName] = 0; 
        updateTeamList(); 
        document.getElementById('teamName').value = '';
    }
}

function updateTeamList() {
    const teamList = document.getElementById('teamList');
    teamList.innerHTML = teams.map(team => `<li>${team}</li>`).join('');
}

document.getElementById('teamName').addEventListener('keydown', function(event) {
    if (event.key === 'Enter') {
        addTeam();
    }
});

function startGame() {
    const themeCheckboxes = document.querySelectorAll('#theme-selection input:checked');
    const selectedThemes = Array.from(themeCheckboxes).map(checkbox => checkbox.value);

    if (selectedThemes.length === 0) {
        alert('Please select at least one theme to start the game.');
        return;
    }

    loadQuestions(selectedThemes);
    document.getElementById('intro-div').style.display = 'none';
    document.getElementById('game-area').style.display = 'block';
    displayQuestion();
}

function loadQuestions(selectedThemes) {
    questions = selectedThemes.reduce((acc, theme) => acc.concat(themes[theme]), []);
    shuffleArray(questions); // Shuffle questions to mix themes
}

function displayQuestion() {
    let availableQuestions = questions.filter((q, index) => !usedQuestions.includes(index));
    if (availableQuestions.length === 0) {
        alert('No more questions available');
        return;
    }
    let randomIndex = Math.floor(Math.random() * availableQuestions.length);
    currentQuestionIndex = questions.indexOf(availableQuestions[randomIndex]);
    usedQuestions.push(currentQuestionIndex);

    const question = questions[currentQuestionIndex];
    document.getElementById('question').innerText = question.question;
    const answersDiv = document.getElementById('answers');
    answersDiv.innerHTML = '';
    question.answers.forEach((answer, index) => {
        answersDiv.innerHTML += `<button onclick="selectAnswer(${index})">${answer}</button>`;
    });
    document.getElementById('next-question').style.display = 'none';
    document.getElementById('teams-correct').style.display = 'none';
    resetAnswerColors();
}

function selectAnswer(index) {
}

function showAnswer() {
    const correctAnswerIndex = questions[currentQuestionIndex].correct;
    document.getElementById('answers').children[correctAnswerIndex].style.backgroundColor = 'antiquewhite';
    displayTeamsCorrect();
}

function displayTeamsCorrect() {
    const teamsCorrectDiv = document.getElementById('teams-correct');
    teamsCorrectDiv.innerHTML = '<h3>Who got it right?</h3>';
    teams.forEach(team => {
        teamsCorrectDiv.innerHTML += `<label><input type="checkbox" value="${team}"> ${team}</label><br>`;
    });
    document.getElementById('next-question').style.display = 'block';
    teamsCorrectDiv.style.display = 'block';
}

function nextQuestion() {
    const teamsCorrect = document.querySelectorAll('#teams-correct input:checked');
    teamsCorrect.forEach(team => {
        scores[team.value]++;
    });
    updateScoreboard();
    clearTeamSelection();
    if (usedQuestions.length < questions.length) {
        displayQuestion();
    } else {
        alert('Game Over');
    }
}

function resetAnswerColors() {
    const answerButtons = document.querySelectorAll('#answers button');
    answerButtons.forEach(button => {
        button.style.backgroundColor = '';
    });
}

function clearTeamSelection() {
    document.getElementById('teams-correct').innerHTML = '';
}

function updateScoreboard() {
    const scoreboard = document.getElementById('scoreboard');
    scoreboard.innerHTML = '';
    for (let team in scores) {
        scoreboard.innerHTML += `<p>${team}: ${scores[team]}</p>`;
    }
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

let themes = {
    geography: [
        { question: "What is the capital of Australia?", answers: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2 },
        { question: "Which river runs through Baghdad?", answers: ["Euphrates", "Nile", "Danube", "Amazon"], correct: 0 },
        { question: "What is the largest country by land area in South America?", answers: ["Brazil", "Argentina", "Colombia", "Peru"], correct: 0 },
        { question: "Which African country was formerly known as Abyssinia?", answers: ["Egypt", "Nigeria", "Ethiopia", "Kenya"], correct: 2 },
        { question: "What is the smallest country in the world by land area?", answers: ["Monaco", "Nauru", "San Marino", "Vatican City"], correct: 3 },
        { question: "In which country would you find the Negev Desert?", answers: ["Israel", "Saudi Arabia", "Egypt", "Iraq"], correct: 0 },
        { question: "What is the longest river in Europe?", answers: ["Volga", "Danube", "Rhine", "Loire"], correct: 0 },
        { question: "Which mountain range stretches across seven countries in Southern Europe?", answers: ["Alps", "Pyrenees", "Apennines", "Carpathians"], correct: 0 },
        { question: "Which sea is the saltiest body of water in the world?", answers: ["Caspian Sea", "Dead Sea", "Red Sea", "Mediterranean Sea"], correct: 1 },
        { question: "What is the only sea without any coastlines?", answers: ["Sargasso Sea", "Celebes Sea", "Ligurian Sea", "Adriatic Sea"], correct: 0 },
        { question: "Which country is known as the 'Land of a Thousand Lakes'?", answers: ["Sweden", "Finland", "Norway", "Canada"], correct: 1 },
        { question: "Which country has the most natural lakes?", answers: ["Canada", "Russia", "United States", "China"], correct: 2 },
        { question: "What is the capital of New Zealand?", answers: ["Auckland", "Wellington", "Christchurch", "Queenstown"], correct: 1 },
        { question: "Which ocean is the largest and deepest on Earth?", answers: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], correct: 2 },
        { question: "In which country would you find Mount Kilimanjaro?", answers: ["Kenya", "Tanzania", "Uganda", "Rwanda"], correct: 1 },
        { question: "Which city is the southernmost capital city in the world?", answers: ["Wellington", "Buenos Aires", "Canberra", "Montevideo"], correct: 3 },
        { question: "What is the smallest country in Africa by land area?", answers: ["Gambia", "Swaziland", "Djibouti", "Seychelles"], correct: 3 },
        { question: "What is the largest island in the Mediterranean Sea?", answers: ["Cyprus", "Sardinia", "Sicily", "Crete"], correct: 2 },
        { question: "Which country is known as the 'Land of the Rising Sun'?", answers: ["China", "Korea", "Japan", "Vietnam"], correct: 2 },
        { question: "What is the capital of Brazil?", answers: ["Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador"], correct: 2 },
        { question: "What is the highest mountain peak in North America?", answers: ["Mount McKinley", "Mount Logan", "Mount St. Elias", "Mount Foraker"], correct: 0 },
        { question: "In which country would you find the ancient city of Petra?", answers: ["Turkey", "Greece", "Jordan", "Lebanon"], correct: 2 },
        { question: "Which city is located furthest south?", answers: ["Punta Arenas", "Ushuaia", "Hobart", "Cape Town"], correct: 1 },
        { question: "What is the capital of Egypt?", answers: ["Cairo", "Alexandria", "Luxor", "Aswan"], correct: 0 },
        { question: "Which African country is known as the 'Pearl of Africa'?", answers: ["Tanzania", "Uganda", "Kenya", "Rwanda"], correct: 1 },
        { question: "Which country has the largest population in Africa?", answers: ["Nigeria", "Ethiopia", "Egypt", "Democratic Republic of the Congo"], correct: 0 },
        { question: "What is the largest city in South Africa?", answers: ["Cape Town", "Durban", "Johannesburg", "Pretoria"], correct: 2 },
        { question: "Which river is the longest in the world?", answers: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], correct: 1 },
        { question: "Which country is the smallest in the world by population?", answers: ["Vatican City", "Monaco", "Nauru", "Tuvalu"], correct: 0 },
        { question: "What is the only country in the world that is also a continent?", answers: ["Australia", "Antarctica", "Greenland", "Madagascar"], correct: 0 },
        { question: "What is the largest city in New Zealand?", answers: ["Auckland", "Wellington", "Christchurch", "Hamilton"], correct: 0 },
        { question: "Which ocean is the warmest?", answers: ["Indian Ocean", "Atlantic Ocean", "Pacific Ocean", "Arctic Ocean"], correct: 0 },
        { question: "In which country would you find the ancient city of Machu Picchu?", answers: ["Brazil", "Argentina", "Chile", "Peru"], correct: 3 },
        { question: "Which mountain range stretches across six countries in Southeast Europe?", answers: ["Alps", "Pyrenees", "Apennines", "Balkan Mountains"], correct: 3 },
        { question: "Which sea is bordered by Europe to the north and Africa to the south?", answers: ["Mediterranean Sea", "BlackSea", "Caspian Sea", "Red Sea"], correct: 0 },
        { question: "What is the largest island in the Caribbean?", answers: ["Jamaica", "Cuba", "Hispaniola", "Puerto Rico"], correct: 1 },
        { question: "Which city is the capital of Canada?", answers: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2 },
        { question: "What is the smallest country in Asia by land area?", answers: ["Maldives", "Singapore", "Brunei", "Lebanon"], correct: 1 },
        { question: "Which African country is known as the 'Rainbow Nation'?", answers: ["Nigeria", "Ghana", "South Africa", "Kenya"], correct: 2 },
        { question: "What is the largest city in Australia?", answers: ["Sydney", "Melbourne", "Brisbane", "Perth"], correct: 1 },
        { question: "Which country has the longest coastline in the world?", answers: ["Canada", "Russia", "United States", "Australia"], correct: 0 },
        { question: "What is the capital of South Korea?", answers: ["Seoul", "Busan", "Incheon", "Daegu"], correct: 0 },
        { question: "In which country would you find the ancient city of Timbuktu?", answers: ["Mali", "Niger", "Chad", "Burkina Faso"], correct: 0 },
        { question: "What is the largest island in Indonesia?", answers: ["Java", "Sumatra", "Borneo", "Papua"], correct: 0 },
        { question: "Which country is known as the 'Land of the Midnight Sun'?", answers: ["Sweden", "Norway", "Finland", "Russia"], correct: 1 },
        { question: "What is the capital of Argentina?", answers: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"], correct: 0 },
        { question: "Which city is the northernmost capital city in the world?", answers: ["Reykjavik", "Helsinki", "Oslo", "Tallinn"], correct: 0 },
        { question: "What is the largest city in Canada by population?", answers: ["Toronto", "Montreal", "Vancouver", "Calgary"], correct: 0 },
        { question: "Which river is the longest in Asia?", answers: ["Yangtze River", "Yellow River", "Mekong River", "Ganges River"], correct: 0 },
        { question: "What is the capital of Turkey?", answers: ["Istanbul", "Ankara", "Izmir", "Bursa"], correct: 1 },
        { question: "In which country would you find the city of Marrakech?", answers: ["Morocco", "Algeria", "Tunisia", "Libya"], correct: 0 },
        { question: "Which country is known as the 'Land of a Thousand Islands'?", answers: ["Indonesia", "Philippines", "Malaysia", "Japan"], correct: 0 },
        { question: "What is the largest city in India?", answers: ["Delhi", "Mumbai", "Kolkata", "Chennai"], correct: 1 },
        { question: "Which African country is known as the 'Land of a Thousand Hills'?", answers: ["Rwanda", "Uganda", "Burundi", "Tanzania"], correct: 0 },
        { question: "What is the capital of Saudi Arabia?", answers: ["Riyadh", "Jeddah", "Mecca", "Medina"], correct: 0 },
        { question: "Which country is known as the 'Land of the Pharaohs'?", answers: ["Egypt", "Syria", "Iraq", "Jordan"], correct: 0 },
        { question: "What is the largest city in South America by population?", answers: ["Sao Paulo", "Buenos Aires", "Rio de Janeiro", "Lima"], correct: 0 },
        { question: "Which sea is bordered by Italy, Croatia, Montenegro, and Albania?", answers: ["Adriatic Sea", "Aegean Sea", "Ionian Sea", "Tyrrhenian Sea"], correct: 0 },
        { question: "What is the capital of Spain?", answers: ["Barcelona", "Madrid", "Valencia", "Seville"], correct: 1 },
        { question: "Which country is the largest producer of coffee in the world?", answers: ["Brazil", "Colombia", "Vietnam", "Ethiopia"], correct: 0 },
        { question: "In which country would you find the city of Casablanca?", answers: ["Morocco", "Algeria", "Tunisia", "Libya"], correct: 0 },
        { question: "What is the largest city in South Korea?", answers: ["Seoul", "Busan", "Incheon", "Daegu"], correct: 0 },
        { question: "Which country is known as the 'Land of Fire and Ice'?", answers: ["Norway", "Iceland", "Greenland", "Finland"], correct: 1 },
        { question: "What is the capital of Peru?", answers: ["Lima", "Cusco", "Arequipa", "Trujillo"], correct: 0 },
        { question: "Which city is the capital of Australia?", answers: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correct: 2 },
        { question: "What is the largest island in Japan?", answers: ["Hokkaido", "Honshu", "Shikoku", "Kyushu"], correct: 1 },
        { question: "Which river flows through Paris?", answers: ["Seine River", "Loire River", "Rhone River", "Garonne River"], correct: 0 },
        { question: "What is the capital of Portugal?", answers: ["Lisbon", "Porto", "Faro", "Coimbra"], correct: 0 },
        { question: "Which country is known as the 'Land of Smiles'?", answers: ["Thailand", "Vietnam", "Laos", "Cambodia"], correct: 0 },
        { question: "What is the largest city in Vietnam?", answers: ["Hanoi", "Ho Chi Minh City", "Haiphong", "Da Nang"], correct: 1 },
        { question: "Which country is known as the 'Land of a Million Elephants'?", answers: ["Thailand", "Vietnam", "Laos", "Cambodia"], correct: 2 },
        { question: "What is the capital of Venezuela?", answers: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto"], correct: 0 },
        { question: "Which city is located at the mouth of the Amazon River?", answers: ["Manaus", "Belem", "Santarem", "Macapá"], correct: 1 },
        { question: "What is the smallest country in Central America by land area?", answers: ["El Salvador", "Honduras", "Costa Rica", "Panama"], correct: 2 },
        { question: "Which river forms part of the border between the United States and Mexico?", answers: ["Rio Grande", "Colorado River", "Missouri River", "Mississippi River"], correct: 0 },
        { question: "What is the largest city in Poland?", answers: ["Warsaw", "Krakow", "Wroclaw", "Poznan"], correct: 0 },
        { question: "Which country is known as the 'Land of the Long White Cloud'?", answers: ["Australia", "New Zealand", "Fiji", "Papua New Guinea"], correct: 1 },
        { question: "What is the capital of Austria?", answers: ["Vienna", "Salzburg", "Innsbruck", "Graz"], correct: 0 },
        { question: "Which river flows through Vienna?", answers: ["Danube River", "Rhine River", "Elbe River", "Main River"], correct: 0 },
        { question: "What is the largest city in Sweden?", answers: ["Stockholm", "Gothenburg", "Malmo", "Uppsala"], correct: 0 },
        { question: "Which country is known as the 'Cradle of Civilization'?", answers: ["Greece", "Egypt", "Iraq", "Iran"], correct: 2 },
        { question: "What is the capital of South Africa?", answers: ["Cape Town", "Durban", "Johannesburg", "Pretoria"], correct: 3 },
        { question: "Which sea is bordered by Europe to the north and Africa to the south?", answers: ["Mediterranean Sea", "Black Sea", "Caspian Sea", "Red Sea"], correct: 0 },
        { question: "What is the largest island in the Caribbean?", answers: ["Jamaica", "Cuba", "Hispaniola","Puerto Rico"], correct: 1 },
        { question: "Which river forms part of the border between Mexico and the United States?", answers: ["Rio Grande", "Mississippi River", "Missouri River", "Colorado River"], correct: 0 },
    ],
    popculture: [
        { question: "Which TV show features characters named Ross, Rachel, Chandler, Monica, Joey, and Phoebe?", answers: ["Friends", "The Office", "How I Met Your Mother", "Seinfeld"], correct: 0 },
        { question: "Who is the lead vocalist of the band 'Queen'?", answers: ["Freddie Mercury", "David Bowie", "Elton John", "Mick Jagger"], correct: 0 },
        { question: "Which movie features a talking pig named Babe?", answers: ["Babe", "Charlotte's Web", "Piglet's Big Movie", "Animal Farm"], correct: 0 },
        { question: "Which artist released the album '25', featuring the hit single 'Hello'?", answers: ["Adele", "Taylor Swift", "Beyoncé", "Rihanna"], correct: 0 },
        { question: "What is the highest-grossing film of all time (as of 2024)?", answers: ["Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"], correct: 1 },
        { question: "Which animated TV series follows the adventures of a boy named Finn and his magical dog Jake?", answers: ["Adventure Time", "Regular Show", "Steven Universe", "Gravity Falls"], correct: 0 },
        { question: "Who played the character of Tony Stark/Iron Man in the Marvel Cinematic Universe?", answers: ["Chris Hemsworth", "Chris Evans", "Robert Downey Jr.", "Mark Ruffalo"], correct: 2 },
        { question: "Which video game franchise features a plumber named Mario?", answers: ["Zelda", "Metroid", "Super Mario", "Donkey Kong"], correct: 2 },
        { question: "Which British author wrote the 'Harry Potter' book series?", answers: ["J.K. Rowling", "Roald Dahl", "C.S. Lewis", "J.R.R. Tolkien"], correct: 0 },
        { question: "Which TV series features a character named Walter White, who starts manufacturing methamphetamine?", answers: ["Breaking Bad", "The Sopranos", "Mad Men", "The Wire"], correct: 0 },
        { question: "Who played the character of Katniss Everdeen in 'The Hunger Games' film series?", answers: ["Emma Stone", "Jennifer Lawrence", "Emma Watson", "Scarlett Johansson"], correct: 1 },
        { question: "Which band is known for their hit song 'Stairway to Heaven'?", answers: ["The Rolling Stones", "Led Zeppelin", "The Beatles", "Pink Floyd"], correct: 1 },
        { question: "Which film won the Academy Award for Best Picture in 2020?", answers: ["Parasite", "1917", "Joker", "Once Upon a Time in Hollywood"], correct: 0 },
        { question: "Which animated film features a young lion named Simba?", answers: ["Finding Nemo", "The Lion King", "Toy Story", "Frozen"], correct: 1 },
        { question: "Which TV series is set in the fictional continents of Westeros and Essos?", answers: ["The Walking Dead", "Game of Thrones", "Stranger Things", "Westworld"], correct: 1 },
        { question: "Who played the character of Jack Dawson in the film 'Titanic'?", answers: ["Tom Cruise", "Leonardo DiCaprio", "Brad Pitt", "Johnny Depp"], correct: 1 },
        { question: "Which artist released the album 'Lemonade' in 2016?", answers: ["Beyoncé", "Rihanna", "Taylor Swift", "Adele"], correct: 0 },
        { question: "Which fictional character lives in a pineapple under the sea?", answers: ["SpongeBob SquarePants", "Patrick Star", "Squidward Tentacles", "Mr. Krabs"], correct: 0 },
        { question: "Which film features a group of seniors who start a successful internship at a tech company?", answers: ["The Intern", "The Social Network", "The Internship", "The Founder"], correct: 2 },
        { question: "Who directed the film 'Jurassic Park'?", answers: ["Steven Spielberg", "James Cameron", "George Lucas", "Peter Jackson"], correct: 0 },
        { question: "Which TV series features a high school chemistry teacher turned methamphetamine manufacturer?", answers: ["Breaking Bad", "The Walking Dead", "Dexter", "Lost"], correct: 0 },
        { question: "Which artist released the album '1989', featuring the hit single 'Shake It Off'?", answers: ["Taylor Swift", "Ariana Grande", "Katy Perry", "Selena Gomez"], correct: 0 },
        { question: "Which film features a young boy named Kevin who is accidentally left behind by his family during Christmas?", answers: ["Home Alone", "Elf", "The Santa Clause", "A Christmas Story"], correct: 0 },
        { question: "Who played the character of Batman in 'The Dark Knight' trilogy?", answers: ["Christian Bale", "Michael Keaton", "Ben Affleck", "George Clooney"], correct: 0 },
        { question: "Which animated film features a robot named WALL-E?", answers: ["Finding Nemo", "The Incredibles", "Ratatouille", "WALL-E"], correct: 3 },    
        { question: "What is the real name of the rapper Eminem?", answers: ["Curtis Jackson", "Calvin Broadus", "Marshall Mathers", "Shawn Carter"], correct: 2 },
        { question: "In which movie did Heath Ledger play the Joker?", answers: ["Batman Begins", "The Dark Knight", "The Dark Knight Rises", "Batman v Superman"], correct: 1 },
        { question: "Which actor voices the character of Groot in the Marvel Cinematic Universe?", answers: ["Bradley Cooper", "Vin Diesel", "Chris Pratt", "Dave Bautista"], correct: 1 },
        { question: "Which TV series features a character named Eleven with psychokinetic abilities?", answers: ["The X-Files", "Stranger Things", "Twin Peaks", "Buffy the Vampire Slayer"], correct: 1 },
        { question: "What is the name of the fictional city where Batman operates?", answers: ["Metropolis", "Star City", "Central City", "Gotham"], correct: 3 },
        { question: "Who is the creator of the animated TV series 'The Simpsons'?", answers: ["Matt Groening", "Seth MacFarlane", "Trey Parker", "Mike Judge"], correct: 0 },
        { question: "Which film won the first Academy Award for Best Picture?", answers: ["Sunrise", "The Jazz Singer", "Wings", "The Broadway Melody"], correct: 2 },
        { question: "Which actor played the role of Neo in 'The Matrix' trilogy?", answers: ["Keanu Reeves", "Laurence Fishburne", "Hugo Weaving", "Joe Pantoliano"], correct: 0 },
        { question: "What is the name of the island in the TV series 'Lost'?", answers: ["The Island", "Oahu", "Mystery Island", "Hydra Island"], correct: 0 },
        { question: "Who wrote the novel 'The Great Gatsby'?", answers: ["F. Scott Fitzgerald", "Ernest Hemingway", "J.D. Salinger", "John Steinbeck"], correct: 0 },
        { question: "Which film features the song 'My Heart Will Go On' by Celine Dion?", answers: ["Armageddon", "Titanic", "The Bodyguard", "Moulin Rouge!"], correct: 1 },
        { question: "Who directed the film 'The Shawshank Redemption'?", answers: ["Steven Spielberg", "Frank Darabont", "Quentin Tarantino", "Martin Scorsese"], correct: 1 },
        { question: "In which city is the TV series 'Breaking Bad' set?", answers: ["Phoenix", "Albuquerque", "Las Vegas", "Denver"], correct: 1 },
        { question: "Who played the character of Captain Jack Sparrow in the 'Pirates of the Caribbean' films?", answers: ["Orlando Bloom", "Geoffrey Rush", "Johnny Depp", "Keira Knightley"], correct: 2 },
        { question: "What is the name of the highest-grossing film of all time (as of 2024)?", answers: ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars: The Force Awakens"], correct: 2 },
        { question: "Which artist released the album 'Thriller'?", answers: ["Prince", "Madonna", "Michael Jackson", "Whitney Houston"], correct: 2 },
        { question: "Who played the character of Harry Potter in the film series?", answers: ["Daniel Radcliffe", "Rupert Grint", "Elijah Wood", "Tom Felton"], correct: 0 },
        { question: "What is the name of the spacecraft in the film '2001: A Space Odyssey'?", answers: ["USS Enterprise", "Discovery One", "Millennium Falcon", "Nostromo"], correct: 1 },
        { question: "Which TV series features characters named Sheldon, Leonard, and Penny?", answers: ["Friends", "How I Met Your Mother", "The Big Bang Theory", "New Girl"], correct: 2 },
        { question: "Who directed the film 'Jurassic Park'?", answers: ["James Cameron", "George Lucas", "Peter Jackson", "Steven Spielberg"], correct: 3 },
        { question: "In which film did Tom Hanks play the character Forrest Gump?", answers: ["Big", "Forrest Gump", "Cast Away", "Saving Private Ryan"], correct: 1 },
        { question: "Which artist released the album 'Back to Black'?", answers: ["Adele", "Amy Winehouse", "Beyoncé", "Rihanna"], correct: 1 },
        { question: "What is the name of the dog in the comic strip 'Peanuts'?", answers: ["Odie", "Scooby-Doo", "Snoopy", "Pluto"], correct: 2 },
        { question: "Which film won the Academy Award for Best Picture in 2019?", answers: ["Green Book", "Black Panther", "BlacKkKlansman", "Bohemian Rhapsody"], correct: 0 },
        { question: "Who directed the film 'Inception'?", answers: ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Quentin Tarantino"], correct: 1 },
        { question: "In which TV series would you find the character Dwight Schrute?", answers: ["Parks and Recreation", "The Office", "Brooklyn Nine-Nine", "30 Rock"], correct: 1 },
        { question: "Who is the lead vocalist of the band Coldplay?", answers: ["Chris Martin", "Brandon Flowers", "Bono", "Dave Grohl"], correct: 0 },
        { question: "Which film features a character named Tony Stark, also known as Iron Man?", answers: ["Spider-Man", "Iron Man", "The Incredible Hulk", "Thor"], correct: 1 },
        { question: "Who played the character of Danny Ocean in the 'Ocean's' film series?", answers: ["Brad Pitt", "George Clooney", "Matt Damon", "Don Cheadle"], correct: 1 },
        { question: "What is the name of the fictional city in which the TV series 'Friends' is set?", answers: ["Los Angeles", "Chicago", "Miami", "New York City"], correct: 3 },
        { question: "Who wrote the novel 'The Catcher in the Rye'?", answers: ["F. Scott Fitzgerald", "Ernest Hemingway", "J.D. Salinger", "John Steinbeck"], correct: 2 },
        { question: "In which film did Leonardo DiCaprio play the character Jack Dawson?", answers: ["Catch Me If You Can", "The Revenant", "Titanic", "Inception"], correct: 2 },
        { question: "Which artist released the album '21'?", answers: ["Adele", "Beyoncé", "Taylor Swift", "Lady Gaga"], correct: 0 },
        { question: "Who played the character of Edward Cullen in the 'Twilight' film series?", answers: ["Taylor Lautner", "Robert Pattinson", "Jackson Rathbone", "Kellan Lutz"], correct: 1 },
        { question: "What is the name of the high school in the TV series 'Buffy the Vampire Slayer'?", answers: ["West Beverly High", "Sunnydale High", "Bayside High", "Liberty High"], correct: 1 },
        { question: "Who directed the film 'The Godfather'?", answers: ["Martin Scorsese", "Francis Ford Coppola", "Steven Spielberg", "Brian De Palma"], correct: 1 },
        { question: "In which film did Robin Williams play the character Genie?", answers: ["Hook", "Jumanji", "Aladdin", "Mrs. Doubtfire"], correct: 2 },
        { question: "Which TV series features a character named Walter White, who starts manufacturing methamphetamine?", answers: ["The Sopranos", "Breaking Bad", "Mad Men", "The Wire"], correct: 1 },
        { question: "Who is the lead singer of the band Maroon 5?", answers: ["Adam Levine", "Bruno Mars", "Chris Martin", "Adam Lambert"], correct: 0 },
        { question: "Which film won the Academy Award for Best Picture in 2020?", answers: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], correct: 2 },
        { question: "Who directed the film 'Avatar'?", answers: ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Ridley Scott"], correct: 2 },
        { question: "In which TV series would you find the character Barney Stinson?", answers: ["How I Met Your Mother", "Friends", "Parks and Recreation", "The Big Bang Theory"], correct: 0 },
        { question: "Who is the author of the 'A Song of Ice and Fire' series of novels?", answers: ["J.K. Rowling", "J.R.R. Tolkien", "George R.R. Martin", "Stephen King"], correct: 2 },
        { question: "Which film features a group of seniors who start a successful internship at a tech company?", answers: ["The Social Network", "The Internship", "The Intern", "Senior Year"], correct: 1 },
        { question: "Who directed the film 'The Dark Knight'?", answers: ["James Cameron", "Christopher Nolan", "Steven Spielberg", "Quentin Tarantino"], correct: 1 },
        { question: "In which film did Julie Andrews play the character Mary Poppins?", answers: ["The Sound of Music", "Mary Poppins", "Victor/Victoria", "Thoroughly Modern Millie"], correct: 1 },
        { question: "Which TV series is set in the fictional continents of Westeros and Essos?", answers: ["Vikings", "Game of Thrones", "The Witcher", "The Last Kingdom"], correct: 1 },
        { question: "Who is the lead guitarist of the band Queen?", answers: ["Brian May", "Jimmy Page", "Slash", "Eric Clapton"], correct: 0 },
        { question: "Which film won the first Academy Award for Best Animated Feature?", answers: ["Shrek", "Toy Story", "Finding Nemo", "The Incredibles"], correct: 0 },
        { question: "Who played the character of Jack Dawson in the film 'Titanic'?", answers: ["Leonardo DiCaprio", "Tom Hanks", "Johnny Depp", "Brad Pitt"], correct: 0 },
        { question: "What is the name of the fictional city in which the TV series 'The Office' is set?", answers: ["Scranton", "Pawnee", "Quahog", "Springfield"], correct: 0 },
        { question: "Who directed the film 'Schindler's List'?", answers: ["James Cameron", "Steven Spielberg", "Martin Scorsese", "Ridley Scott"], correct: 1 },
        { question: "In which film did Emma Stone play the character Mia Dolan?", answers: ["Easy A", "Birdman", "The Help", "La La Land"], correct: 3 },
        { question: "Which TV series features a character named Tony Soprano?", answers: ["The Wire", "The Sopranos", "Breaking Bad", "Mad Men"], correct: 1 },
        { question: "Who is the lead singer of the band U2?", answers: ["Sting", "Bono", "Mick Jagger", "Freddie Mercury"], correct: 1 },
        { question: "Which film won the Academy Award for Best Picture in 2018?", answers: ["The Shape of Water", "Three Billboards Outside Ebbing, Missouri", "Lady Bird", "Get Out"], correct: 0 },
        { question: "Who directed the film 'Forrest Gump'?", answers: ["Steven Spielberg", "Robert Zemeckis", "Ron Howard", "James Cameron"], correct: 1 },
        { question: "In which TV series would you find the character Arya Stark?", answers: ["Vikings", "Game of Thrones", "The Witcher", "The Last Kingdom"], correct: 1 },
        { question: "Who is the author of the 'Harry Potter' book series?", answers: ["J.R.R. Tolkien", "C.S. Lewis", "J.K. Rowling", "Philip Pullman"], correct: 2 },
        { question: "Which film features the song 'Let It Go'?", answers: ["Tangled", "Moana", "Frozen", "Brave"], correct: 2 },
        { question: "Who played the character of Batman in 'The Dark Knight' trilogy?", answers: ["Michael Keaton", "Ben Affleck", "Christian Bale", "George Clooney"], correct: 2 },
        { question: "What is the name of the fictional high school in the TV series 'Glee'?", answers: ["West Beverly High", "Sunnydale High", "Bayside High", "William McKinley High"], correct: 3 },
        { question: "Who directed the film 'The Silence of the Lambs'?", answers: ["Ridley Scott", "Jonathan Demme", "David Fincher", "Martin Scorsese"], correct: 1 },
        { question: "In which film did Sandra Bullock play the character Leigh Anne Tuohy?", answers: ["Gravity", "Miss Congeniality", "The Blind Side", "Speed"], correct: 2 },
        { question: "Which TV series features characters named Ross, Rachel, Chandler, Monica, Joey, and Phoebe?", answers: ["Friends", "How I Met Your Mother", "Seinfeld", "The Big Bang Theory"], correct: 0 },
        { question: "Who is the lead vocalist of the band Nirvana?", answers: ["Eddie Vedder", "Chris Cornell", "Kurt Cobain", "Dave Grohl"], correct: 2 },
        { question: "Which film won the Academy Award for Best Picture in 2017?", answers: ["Moonlight", "La La Land", "Manchester by the Sea", "Arrival"], correct: 0 },
        { question: "Who directed the film 'Gone with the Wind'?", answers: ["Victor Fleming", "David O. Selznick", "George Cukor", "William Wyler"], correct: 0 },
        { question: "In which TV series would you find the character Tyrion Lannister?", answers: ["Vikings", "Game of Thrones", "The Witcher", "The Last Kingdom"], correct: 1 },
        { question: "Who is the lead singer of the band Foo Fighters?", answers: ["Kurt Cobain", "Chris Cornell", "Dave Grohl", "Eddie Vedder"], correct: 2 },
        { question: "Which film features a character named Rick Deckard?", answers: ["Minority Report", "Blade Runner", "Total Recall", "A.I. Artificial Intelligence"], correct: 1 },
        { question: "Who played the character of Hermione Granger in the 'Harry Potter' film series?", answers: ["Emma Stone", "Emma Watson", "Natalie Portman", "Kristen Stewart"], correct: 1 },
        { question: "What is the name of the school in the TV series 'Saved by the Bell'?", answers: ["Beverly Hills High", "Liberty High", "Bayside High", "West Beverly High"], correct: 2 },
        { question: "Which film won the Academy Award for Best Picture in 2016?", answers: ["Spotlight", "The Revenant", "Mad Max: Fury Road", "The Big Short"], correct: 0 },
        { question: "Who directed the film 'The Lord of the Rings: The Return of the King'?", answers: ["Peter Jackson", "Steven Spielberg", "George Lucas", "James Cameron"], correct: 0 },
        { question: "In which film did Tom Cruise play the character Ethan Hunt?", answers: ["Top Gun", "Minority Report", "Mission: Impossible", "War of the Worlds"], correct: 2 },
        { question: "Which TV series features a character named Michael Scott?", answers: ["Parks and Recreation", "Brooklyn Nine-Nine", "The Office", "30 Rock"], correct: 2 },
        { question: "Who is the lead guitarist of the band The Rolling Stones?", answers: ["Jimmy Page", "Eric Clapton", "Keith Richards", "Brian May"], correct: 2 },
        { question: "Which film won the Academy Award for Best Picture in 2015?", answers: ["Birdman", "The Grand Budapest Hotel", "Whiplash", "Boyhood"], correct: 0 },
        { question: "Who directed the film 'The Matrix'?", answers: ["James Cameron", "Christopher Nolan", "The Wachowskis", "Ridley Scott"], correct: 2 },
        { question: "In which TV series would you find the character Walter White?", answers: ["The Sopranos", "Breaking Bad", "Mad Men", "The Wire"], correct: 1 },
        { question: "Who is the lead singer of the band Radiohead?", answers: ["Thom Yorke", "Chris Martin", "Bono", "Dave Grohl"], correct: 0 },
        { question: "Which film features a character named Tyler Durden?", answers: ["The Social Network", "Fight Club", "American Psycho", "Se7en"], correct: 1 },
        { question: "Who played the character of Rey in the 'Star Wars' sequel trilogy?", answers: ["Daisy Ridley", "Felicity Jones", "Natalie Portman", "Keira Knightley"], correct: 0 },
        { question: "What is the name of the fictional town in the TV series 'Stranger Things'?", answers: ["Hawkins", "Riverdale", "Sunnydale", "Mystic Falls"], correct: 0 },
        { question: "Which film won the Academy Award for Best Picture in 2014?", answers: ["12 Years a Slave", "Gravity", "American Hustle", "The Wolf of Wall Street"], correct: 0 },
        { question: "Who directed the film 'The Lord of the Rings: The Fellowship of the Ring'?", answers: ["Peter Jackson", "Steven Spielberg", "George Lucas", "James Cameron"], correct: 0 },
        { question: "In which film did Julia Roberts play the character Vivian Ward?", answers: ["Notting Hill", "My Best Friend's Wedding", "Pretty Woman", "Runaway Bride"], correct: 2 },
        { question: "Which TV series features a character named Michael Scofield?", answers: ["Lost", "24", "Prison Break", "Dexter"], correct: 2 },
                
    ],
    general: [
        { question: "What is the largest planet in our solar system?", answers: ["Earth", "Jupiter", "Mars", "Saturn"], correct: 1 },
        { question: "Who wrote 'To Kill a Mockingbird'?", answers: ["Harper Lee", "J.K. Rowling", "Ernest Hemingway", "F. Scott Fitzgerald"], correct: 0 },
        { question: "Which element has the chemical symbol 'O'?", answers: ["Gold", "Oxygen", "Iron", "Helium"], correct: 1 },
        { question: "What is the smallest country in the world?", answers: ["Monaco", "Nauru", "San Marino", "Vatican City"], correct: 3 },
        { question: "Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Leonardo da Vinci"], correct: 3 },
        { question: "Which planet is known as the Red Planet?", answers: ["Earth", "Venus", "Mars", "Jupiter"], correct: 2 },
        { question: "Who discovered penicillin?", answers: ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Gregor Mendel"], correct: 1 },
        { question: "What is the hardest natural substance on Earth?", answers: ["Gold", "Iron", "Diamond", "Platinum"], correct: 2 },
        { question: "In which year did the Titanic sink?", answers: ["1912", "1905", "1923", "1898"], correct: 0 },
        { question: "Which organ in the human body is primarily responsible for detoxifying chemicals?", answers: ["Liver", "Heart", "Lungs", "Kidneys"], correct: 0 },
        { question: "What is the tallest mountain in the world?", answers: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"], correct: 2 },
        { question: "Who wrote the play 'Romeo and Juliet'?", answers: ["Charles Dickens", "Jane Austen", "William Shakespeare", "Mark Twain"], correct: 2 },
        { question: "Which element has the atomic number 1?", answers: ["Helium", "Hydrogen", "Carbon", "Oxygen"], correct: 1 },
        { question: "What is the main ingredient in traditional Japanese miso soup?", answers: ["Soybeans", "Rice", "Fish", "Seaweed"], correct: 0 },
        { question: "What is the longest river in the world?", answers: ["Nile", "Amazon", "Yangtze", "Mississippi"], correct: 1 },
        { question: "What is the smallest unit of life?", answers: ["Atom", "Molecule", "Cell", "Organ"], correct: 2 },
        { question: "Which planet is closest to the sun?", answers: ["Venus", "Earth", "Mercury", "Mars"], correct: 2 },
        { question: "What is the chemical symbol for gold?", answers: ["Gd", "Ag", "Au", "Pb"], correct: 2 },
        { question: "Who was the first person to walk on the moon?", answers: ["Buzz Aldrin", "Michael Collins", "Yuri Gagarin", "Neil Armstrong"], correct: 3 },
        { question: "Which gas is most abundant in the Earth's atmosphere?", answers: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"], correct: 2 },
        { question: "What is the smallest bone in the human body?", answers: ["Femur", "Stapes", "Ulna", "Tibia"], correct: 1 },
        { question: "Who invented the telephone?", answers: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], correct: 2 },
        { question: "Which continent is the Sahara Desert located on?", answers: ["Asia", "Australia", "North America", "Africa"], correct: 3 },
        { question: "Who wrote the novel '1984'?", answers: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Arthur C. Clarke"], correct: 0 },
        { question: "What is the largest mammal in the world?", answers: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], correct: 1 },
        { question: "Which planet is known for its rings?", answers: ["Jupiter", "Saturn", "Neptune", "Uranus"], correct: 1 },
        { question: "What is the square root of 64?", answers: ["6", "7", "8", "9"], correct: 2 },
        { question: "Who is known as the 'Father of Computers'?", answers: ["Charles Babbage", "Alan Turing", "John von Neumann", "Bill Gates"], correct: 0 },
        { question: "What is the capital of Canada?", answers: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correct: 3 },
        { question: "Which organ is responsible for pumping blood throughout the body?", answers: ["Lungs", "Liver", "Brain", "Heart"], correct: 3 },
        { question: "Who painted the ceiling of the Sistine Chapel?", answers: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], correct: 1 },
        { question: "What is the most spoken language in the world?", answers: ["English", "Spanish", "Mandarin Chinese", "Hindi"], correct: 2 },
        { question: "Which ocean is the largest?", answers: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3 },
        { question: "What is the chemical formula for water?", answers: ["H2O", "CO2", "O2", "H2"], correct: 0 },
        { question: "Who was the first President of the United States?", answers: ["John Adams", "Thomas Jefferson", "George Washington", "James Madison"], correct: 2 },
        { question: "Which planet is known as the Earth's twin?", answers: ["Mars", "Venus", "Mercury", "Jupiter"], correct: 1 },
        { question: "What is the largest organ in the human body?", answers: ["Liver", "Heart", "Skin", "Lungs"], correct: 2 },
        { question: "Who wrote the play 'Hamlet'?", answers: ["Arthur Miller", "Tennessee Williams", "William Shakespeare", "Oscar Wilde"], correct: 2 },
        { question: "What is the chemical symbol for sodium?", answers: ["Na", "So", "S", "N"], correct: 0 },
        { question: "Who developed the theory of relativity?", answers: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], correct: 1 },
        { question: "What is the capital of Japan?", answers: ["Beijing", "Seoul", "Tokyo", "Bangkok"], correct: 2 },
        { question: "What is the powerhouse of the cell?", answers: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"], correct: 2 },
        { question: "Which element has the chemical symbol 'Fe'?", answers: ["Fluorine", "Iron", "Francium", "Fermium"], correct: 1 },
        { question: "Who wrote 'Pride and Prejudice'?", answers: ["Charlotte Bronte", "Jane Austen", "Emily Bronte", "Mary Shelley"], correct: 1 },
        { question: "What is the fastest land animal?", answers: ["Cheetah", "Lion", "Horse", "Gazelle"], correct: 0 },
        { question: "What is the capital of Italy?", answers: ["Florence", "Venice", "Milan", "Rome"], correct: 3 },
        { question: "Which planet is known as the Morning Star or the Evening Star?", answers: ["Mercury", "Venus", "Mars", "Saturn"], correct: 1 },
        { question: "What is the boiling point of water in Celsius?", answers: ["50°C", "100°C", "150°C", "200°C"], correct: 1 },
        { question: "Who is the author of 'Harry Potter' series?", answers: ["J.R.R. Tolkien", "J.K. Rowling", "C.S. Lewis", "George R.R. Martin"], correct: 1 },
        { question: "What is the capital of the United Kingdom?", answers: ["Edinburgh", "Cardiff", "London", "Dublin"], correct: 2 },
        { question: "Which element has the atomic number 79?", answers: ["Silver", "Gold", "Platinum", "Lead"], correct: 1 },
        { question: "Who wrote the novel 'Moby-Dick'?", answers: ["Mark Twain", "Herman Melville", "Ernest Hemingway", "F. Scott Fitzgerald"], correct: 1 },
        { question: "What is the largest internal organ in the human body?", answers: ["Heart", "Lungs", "Liver", "Kidneys"], correct: 2 },
        { question: "What is the capital of Germany?", answers: ["Munich", "Frankfurt", "Berlin", "Hamburg"], correct: 2 },
        { question: "What is the chemical formula for carbon dioxide?", answers: ["CO", "CO2", "O2", "C2O"], correct: 1 },
        { question: "Who was the first woman to fly solo across the Atlantic?", answers: ["Bessie Coleman", "Amelia Earhart", "Harriet Quimby", "Jacqueline Cochran"], correct: 1 },
        { question: "What is the capital of Russia?", answers: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"], correct: 0 },
        { question: "Who wrote 'The Great Gatsby'?", answers: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "T.S. Eliot"], correct: 1 },
        { question: "What is the most widely spoken language in Brazil?", answers: ["Spanish", "Portuguese", "French", "English"], correct: 1 },
        { question: "Which element is known as the 'King of the Elements'?", answers: ["Hydrogen", "Oxygen", "Carbon", "Gold"], correct: 3 },
        { question: "Who discovered America?", answers: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook"], correct: 0 },
        { question: "What is the capital of Egypt?", answers: ["Alexandria", "Cairo", "Giza", "Luxor"], correct: 1 },
        { question: "Which gas is used in the process of photosynthesis?", answers: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correct: 2 },
        { question: "What is the largest bone in the human body?", answers: ["Humerus", "Femur", "Tibia", "Fibula"], correct: 1 },
        { question: "Who painted 'Starry Night'?", answers: ["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Edvard Munch"], correct: 2 },
        { question: "What is the capital of Spain?", answers: ["Barcelona", "Seville", "Madrid", "Valencia"], correct: 2 },
        { question: "Which planet is known for having a Great Red Spot?", answers: ["Mars", "Saturn", "Jupiter", "Uranus"], correct: 2 },
        { question: "What is the primary language spoken in Australia?", answers: ["French", "Spanish", "Mandarin", "English"], correct: 3 },
        { question: "Who wrote the novel 'Jane Eyre'?", answers: ["Emily Bronte", "Jane Austen", "Charlotte Bronte", "Mary Shelley"], correct: 2 },
        { question: "What is the largest ocean on Earth?", answers: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3 },
        { question: "Who developed the theory of evolution?", answers: ["Gregor Mendel", "Isaac Newton", "Charles Darwin", "Albert Einstein"], correct: 2 },
        { question: "What is the capital of China?", answers: ["Shanghai", "Hong Kong", "Beijing", "Guangzhou"], correct: 2 },
        { question: "What is the smallest planet in our solar system?", answers: ["Earth", "Mercury", "Venus", "Mars"], correct: 1 },
        { question: "Who painted 'The Last Supper'?", answers: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Titian"], correct: 2 },
        { question: "What is the capital of India?", answers: ["Mumbai", "Kolkata", "Chennai", "New Delhi"], correct: 3 },
        { question: "What is the main ingredient in guacamole?", answers: ["Tomato", "Cucumber", "Avocado", "Lettuce"], correct: 2 },
        { question: "Who is the author of 'The Catcher in the Rye'?", answers: ["J.D. Salinger", "Harper Lee", "F. Scott Fitzgerald", "Ernest Hemingway"], correct: 0 },
        { question: "What is the largest desert in the world?", answers: ["Sahara", "Arabian", "Gobi", "Antarctic"], correct: 3 },
        { question: "Who wrote the play 'Macbeth'?", answers: ["Arthur Miller", "William Shakespeare", "Oscar Wilde", "Tennessee Williams"], correct: 1 },
        { question: "What is the chemical symbol for potassium?", answers: ["P", "K", "Po", "Pt"], correct: 1 },
        { question: "Who is known as the 'Mother of Modern Physics'?", answers: ["Rosalind Franklin", "Marie Curie", "Ada Lovelace", "Lise Meitner"], correct: 1 },
        { question: "What is the capital of Brazil?", answers: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correct: 2 },
        { question: "Which planet has the most moons?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correct: 3 },
        { question: "What is the chemical formula for table salt?", answers: ["NaCl", "KCl", "CaCl2", "MgCl2"], correct: 0 },
        { question: "Who wrote the novel 'War and Peace'?", answers: ["Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"], correct: 1 },
    ],
    history: [
        { question: "In what year did World War I begin?", answers: ["1914", "1915", "1916", "1917"], correct: 0 },
        { question: "Which ancient civilization built the Machu Picchu complex?", answers: ["Maya", "Aztec", "Inca", "Egyptian"], correct: 2 },
        { question: "Who was the first female Prime Minister of the United Kingdom?", answers: ["Margaret Thatcher", "Theresa May", "Indira Gandhi", "Queen Elizabeth II"], correct: 0 },
        { question: "Which famous speech did Martin Luther King Jr. deliver in 1963?", answers: ["I Have a Dream", "Give Me Liberty or Give Me Death", "Tear Down This Wall", "The Ballot or the Bullet"], correct: 0 },
        { question: "In what year did the Titanic sink?", answers: ["1912", "1905", "1923", "1898"], correct: 0 },
        { question: "Who was the first European explorer to reach India by sea?", answers: ["Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Marco Polo"], correct: 2 },
        { question: "Which war was fought between the North and South regions of the United States?", answers: ["Revolutionary War", "Civil War", "World War I", "World War II"], correct: 1 },
        { question: "Who was the longest-reigning monarch in British history?", answers: ["Queen Victoria", "Queen Elizabeth II", "King George III", "King Henry VIII"], correct: 0 },
        { question: "What event marked the beginning of World War II?", answers: ["Invasion of Poland", "Bombing of Pearl Harbor", "Battle of Stalingrad", "D-Day"], correct: 0 },
        { question: "Who was the first female pharaoh of ancient Egypt?", answers: ["Hatshepsut", "Cleopatra", "Nefertiti", "Isis"], correct: 0 },
        { question: "Which ancient wonder was located in Alexandria, Egypt?", answers: ["Great Pyramid of Giza", "Colossus of Rhodes", "Lighthouse of Alexandria", "Hanging Gardens of Babylon"], correct: 2 },
        { question: "Who was the founder of the Mongol Empire?", answers: ["Genghis Khan", "Kublai Khan", "Attila the Hun", "Tamerlane"], correct: 0 },
        { question: "Which city was the capital of the Byzantine Empire?", answers: ["Rome", "Athens", "Constantinople", "Alexandria"], correct: 2 },
        { question: "What was the name of the ship that carried the Pilgrims to America in 1620?", answers: ["Mayflower", "Santa Maria", "Golden Hind", "Susan Constant"], correct: 0 },
        { question: "Which famous document begins with the words 'When in the course of human events'?", answers: ["Magna Carta", "Declaration of Independence", "Bill of Rights", "Constitution of the United States"], correct: 1 },
        { question: "Who was the first female president in the world?", answers: ["Margaret Thatcher", "Golda Meir", "Indira Gandhi", "Sirimavo Bandaranaike"], correct: 3 },
        { question: "Which famous scientist formulated the theory of general relativity?", answers: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"], correct: 1 },
        { question: "What event led to the outbreak of the Korean War in 1950?", answers: ["Assassination of Archduke Franz Ferdinand", "Attack on Pearl Harbor", "Invasion of South Korea by North Korea", "Fall of the Berlin Wall"], correct: 2 },
        { question: "Who was the first Emperor of Rome?", answers: ["Julius Caesar", "Augustus", "Nero", "Caligula"], correct: 1 },
        { question: "What was the name of the ship that Charles Darwin sailed on during his voyage to the Galapagos Islands?", answers: ["Endeavour", "Beagle", "Discovery", "Adventure"], correct: 1 },
        { question: "Which famous speech did Abraham Lincoln deliver during the American Civil War?", answers: ["Emancipation Proclamation", "Gettysburg Address", "I Have a Dream", "March on Washington"], correct: 1 },
        { question: "Who was the first African American to serve as President of the United States?", answers: ["Barack Obama", "Martin Luther King Jr.", "Malcolm X", "Nelson Mandela"], correct: 0 },
        { question: "Which country was the first to launch a satellite into space?", answers: ["United States", "Russia", "China", "Germany"], correct: 1 },
        { question: "Who was the first female Prime Minister of India?", answers: ["Sonia Gandhi", "Indira Gandhi", "Margaret Thatcher", "Golda Meir"], correct: 1 },
        { question: "Which city was the site of the first modern Olympic Games in 1896?", answers: ["London", "Paris", "Athens", "Rome"], correct: 2 },
        { question: "Who was the first European explorer to reach the Americas?", answers: ["Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Amerigo Vespucci"], correct: 3 },
        { question: "Which country was the first to declare war in World War II?", answers: ["Germany", "Japan", "Italy", "Poland"], correct: 3 },
        { question: "Who was the first female ruler of England?", answers: ["Elizabeth I", "Mary I", "Anne", "Victoria"], correct: 0 },
        { question: "What was the name of the ship that sank in 1912 on its maiden voyage?", answers: ["Lusitania", "Titanic", "Britannic", "Empress of Ireland"], correct: 1 },
        { question: "Who was the first President of the United States to be impeached?", answers: ["Andrew Johnson", "Richard Nixon", "Bill Clinton", "Donald Trump"], correct: 0 },
        { question: "What year did the United States enter World War II?", answers: ["1939", "1940", "1941", "1942"], correct: 2 },
        { question: "Who was the first female astronaut?", answers: ["Valentina Tereshkova", "Sally Ride", "Yelena Serova", "Mae Jemison"], correct: 0 },
        { question: "Who was the first person to step foot on the moon?", answers: ["Neil Armstrong", "Buzz Aldrin", "Michael Collins", "Alan Shepard"], correct: 0 },
        { question: "Which war was known as the 'War to End All Wars'?", answers: ["World War I", "World War II", "Cold War", "Vietnam War"], correct: 0 },
        { question: "Who was the first female ruler of Russia?", answers: ["Catherine the Great", "Elizabeth I", "Anne", "Alexandra Feodorovna"], correct: 0 },
        { question: "Which American inventor is often credited with inventing the light bulb?", answers: ["Thomas Edison", "Benjamin Franklin", "Nikola Tesla", "Alexander Graham Bell"], correct: 0 },
        { question: "In what year did the Berlin Wall fall, marking the end of the Cold War?", answers: ["1985", "1987", "1989", "1991"], correct: 2 },
        { question: "Who was the first female president of Ireland?", answers: ["Mary Robinson", "Mary McAleese", "Mary Robinson", "Mary Robinson"], correct: 0 },
        { question: "Which country was the first to give women the right to vote?", answers: ["United States", "United Kingdom", "New Zealand", "Australia"], correct: 2 },
        { question: "Who was the first woman to win a Nobel Prize?", answers: ["Marie Curie", "Mother Teresa", "Rosalind Franklin", "Jane Goodall"], correct: 0 },
        { question: "Which famous document begins with the words 'We the People'?", answers: ["Declaration of Independence", "Bill of Rights", "Constitution of the United States", "Emancipation Proclamation"], correct: 2 },
        { question: "What was the code name for the Allied invasion of Normandy during World War II?", answers: ["Operation Overlord", "Operation Barbarossa", "Operation Neptune", "Operation Market Garden"], correct: 0 },
        { question: "Who was the first female pilot to fly solo across the Atlantic Ocean?", answers: ["Amelia Earhart", "Bessie Coleman", "Jacqueline Cochran", "Harriet Quimby"], correct: 0 },
        { question: "Which European country was the first to establish colonies in the Americas?", answers: ["Spain", "Portugal", "France", "England"], correct: 0 },
        { question: "Who was the first Roman Emperor to convert to Christianity?", answers: ["Nero", "Constantine the Great", "Julius Caesar", "Augustus"], correct: 1 },
        { question: "What event sparked the beginning of World War I?", answers: ["Assassination of Archduke Franz Ferdinand", "Invasion of Poland", "Bombing of Pearl Harbor", "Signing of the Treaty of Versailles"], correct: 0 },
        { question: "Which ancient civilization is known for its pyramids?", answers: ["Maya", "Inca", "Aztec", "Egyptian"], correct: 3 },
        { question: "Who was the first female president of the United Nations General Assembly?", answers: ["Eleanor Roosevelt", "Margaret Thatcher", "Angela Merkel", "Vijaya Lakshmi Pandit"], correct: 3 },
        { question: "Which country was the first to abolish slavery?", answers: ["United States", "France", "United Kingdom", "Haiti"], correct: 3 },
        { question: "Who was the first female prime minister of Australia?", answers: ["Julia Gillard", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"], correct: 0 },
        { question: "Which famous leader was assassinated on March 15, 44 BC?", answers: ["Julius Caesar", "Alexander the Great", "Napoleon Bonaparte", "Genghis Khan"], correct: 0 },
        { question: "Who was the first woman to be awarded the Nobel Prize in Literature?", answers: ["Virginia Woolf", "Toni Morrison", "Pearl S. Buck", "Selma Lagerlöf"], correct: 3 },
        { question: "Who was the first female aviator to fly solo across the Atlantic Ocean?", answers: ["Amelia Earhart", "Bessie Coleman", "Jacqueline Cochran", "Harriet Quimby"], correct: 0 },
        { question: "Which American president is known for the Louisiana Purchase?", answers: ["Thomas Jefferson", "James Madison", "John Adams", "Andrew Jackson"], correct: 0 },
        { question: "Who was the first female Secretary of State in the United States?", answers: ["Condoleezza Rice", "Madeleine Albright", "Hillary Clinton", "Susan Rice"], correct: 1 },
        { question: "Which ancient civilization is known for its terracotta army?", answers: ["Maya", "Aztec", "Inca", "Chinese"], correct: 3 },
        { question: "Who was the first female president of Argentina?", answers: ["Cristina Fernández de Kirchner", "Isabel Perón", "Eva Perón", "Cristina Fernández de Kirchner"], correct: 1 },
        { question: "Which country was the first to host the modern Olympic Games?", answers: ["United Kingdom", "Greece", "France", "United States"], correct: 1 },
        { question: "Who was the first female prime minister of Israel?", answers: ["Golda Meir", "Benazir Bhutto", "Margaret Thatcher", "Indira Gandhi"], correct: 0 },
        { question: "Which ancient civilization is known for its alphabet?", answers: ["Maya", "Inca", "Aztec", "Phoenician"], correct: 3 },
        { question: "Who was the first female president of Brazil?", answers: ["Dilma Rousseff", "Fernanda Montenegro", "Maria da Penha", "Dilma Rousseff"], correct: 0 },
        { question: "Which country was the first to send an artificial satellite into space?", answers: ["United States", "Russia", "China", "Germany"], correct: 1 },
        { question: "Who was the first female president of Chile?", answers: ["Michelle Bachelet", "Evelyn Matthei", "Isabel Allende", "Michelle Bachelet"], correct: 0 },
        { question: "Who was the first female president of Liberia?", answers: ["Ellen Johnson Sirleaf", "Ruth Perry", "Angie Elizabeth Brooks", "Ellen Johnson Sirleaf"], correct: 0 },
        { question: "Which ancient civilization is known for its aqueducts?", answers: ["Maya", "Aztec", "Inca", "Roman"], correct: 3 },
        { question: "Who was the first female prime minister of Canada?", answers: ["Kim Campbell", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"], correct: 0 },
        { question: "Who was the first female president of South Korea?", answers: ["Park Geun-hye", "Chun Doo-hwan", "Kim Dae-jung", "Park Geun-hye"], correct: 0 },
        { question: "Which American president is known for the policy of 'New Deal'?", answers: ["Franklin D. Roosevelt", "Theodore Roosevelt", "Herbert Hoover", "Woodrow Wilson"], correct: 0 },
    ],
    technology: [
        { question: "Who is known as the father of computer science?", answers: ["Alan Turing", "Charles Babbage", "Ada Lovelace", "John von Neumann"], correct: 0 },
        { question: "What does the abbreviation 'HTTP' stand for in website addresses?", answers: ["Hypertext Transfer Protocol", "High Tech Transfer Process", "Hyperlink Text Transfer Process", "Hypertext Test Transfer Protocol"], correct: 0 },
        { question: "Which company was founded by Bill Gates and Paul Allen in 1975?", answers: ["Microsoft", "Apple", "Google", "Amazon"], correct: 0 },
        { question: "What does 'www' stand for in a website browser?", answers: ["World Wide Web", "Web World Wires", "Web Wide World", "World Web Wires"], correct: 0 },
        { question: "Who is credited with inventing the World Wide Web?", answers: ["Tim Berners-Lee", "Steve Jobs", "Bill Gates", "Larry Page"], correct: 0 },
        { question: "What is the main purpose of a firewall?", answers: ["To protect a computer network from unauthorized access", "To improve internet speed", "To block pop-up ads", "To store website data"], correct: 0 },
        { question: "Which programming language is commonly used for web development?", answers: ["JavaScript", "Python", "Java", "C++"], correct: 0 },
        { question: "What is the process of converting information into a code to prevent unauthorized access?", answers: ["Encryption", "Decryption", "Encoding", "Decoding"], correct: 0 },
        { question: "What does 'SEO' stand for in the context of websites?", answers: ["Search Engine Optimization", "Secure Email Option", "System Enhancement Opportunity", "Site Engine Organization"], correct: 0 },
        { question: "Which technology company was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne?", answers: ["Apple", "Microsoft", "Google", "Amazon"], correct: 0 },
        { question: "Which computer hardware device provides an interface for all other connected devices to communicate?", answers: ["Motherboard", "Central Processing Unit", "Hard Disk Drive", "Random Access Memory"], correct: 0 },
        { question: "What is the purpose of a QR code?", answers: ["To store information that can be scanned and read quickly by a smartphone", "To provide directions to a location", "To play a video", "To send a text message"], correct: 0 },
        { question: "What does the term 'HTML' stand for in web design?", answers: ["Hypertext Markup Language", "Hyperlinks and Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Textual Markup Language"], correct: 0 },
        { question: "What is the name for a small piece of code that is used to track user activity on a website?", answers: ["Cookie", "Biscuit", "Cracker", "Tracker"], correct: 0 },
        { question: "What is the process of copying software programs from secondary storage media to the hard drive called?", answers: ["Installation", "Configuration", "Download", "Backup"], correct: 0 },
        { question: "What is the term for a computer program that replicates itself and spreads to other computers?", answers: ["Virus", "Malware", "Worm", "Trojan Horse"], correct: 0 },
        { question: "Which technology company developed the Android operating system?", answers: ["Google", "Apple", "Microsoft", "Amazon"], correct: 0 },
        { question: "What is the name for a program that appears to be legitimate but is designed to cause damage?", answers: ["Trojan Horse", "Spyware", "Adware", "Worm"], correct: 0 },
        { question: "Which technology company developed the 'iPad' tablet?", answers: ["Apple", "Microsoft", "Google", "Amazon"], correct: 0 },
        { question: "What does the term 'IP address' stand for in internet terminology?", answers: ["Internet Protocol address", "Internet Provider address", "Internet Personal address", "Internet Primary address"], correct: 0 },
        { question: "Which technology company was founded by Larry Page and Sergey Brin?", answers: ["Google", "Apple", "Microsoft", "Amazon"], correct: 0 },
        { question: "What is the term for a network of remote servers hosted on the internet to store, manage, and process data?", answers: ["Cloud Computing", "Virtual Reality", "Artificial Intelligence", "Blockchain"], correct: 0 },
        { question: "Which programming language is often used for developing mobile apps?", answers: ["Java", "Swift", "Python", "C#"], correct: 0 },
        { question: "What is the term for a type of attack that floods a website with traffic to make it unavailable?", answers: ["DDoS attack", "Phishing attack", "Malware attack", "SQL injection"], correct: 0 },
        { question: "What is the name for a software program that displays unwanted advertisements?", answers: ["Adware", "Spyware", "Malware", "Virus"], correct: 0 },
        { question: "Which technology company developed the 'iPhone'?", answers: ["Apple", "Microsoft", "Google", "Amazon"], correct: 0 },
        { question: "What is the term for a program that can replicate itself and spread to other computers?", answers: ["Worm", "Virus", "Trojan Horse", "Spyware"], correct: 0 },
        { question: "Which programming language is often used for building websites?", answers: ["HTML", "Python", "Java", "C++"], correct: 0 },
        { question: "What does the abbreviation 'URL' stand for in web addresses?", answers: ["Uniform Resource Locator", "Universal Reference Link", "User Requested Link", "Uniform Reference Link"], correct: 0 },
        { question: "Which technology company was founded by Jeff Bezos?", answers: ["Amazon", "Apple", "Microsoft", "Google"], correct: 0 },
        { question: "What is the term for a computer program that is disguised as a legitimate program?", answers: ["Trojan Horse", "Virus", "Worm", "Spyware"], correct: 0 },
        { question: "Which programming language is often used for game development?", answers: ["C++", "Python", "Java", "JavaScript"], correct: 0 },
        { question: "What does 'LAN' stand for in computer networking?", answers: ["Local Area Network", "Long Access Network", "Laptop Area Network", "Large Array Network"], correct: 0 },
        { question: "Which technology company developed the 'Windows' operating system?", answers: ["Microsoft", "Apple", "Google", "Amazon"], correct: 0 },
        { question: "What is the term for a software program that can be used to access and manage email?", answers: ["Email Client", "Browser", "Server", "Firewall"], correct: 0 },
        { question: "Which programming language is often used for data analysis?", answers: ["Python", "Java", "C++", "JavaScript"], correct: 0 },
        { question: "What does 'ISP' stand for in internet terminology?", answers: ["Internet Service Provider", "Internet Security Protocol", "Internet System Provider", "Internet Support Program"], correct: 0 },
        { question: "Which technology company was founded by Larry Ellison?", answers: ["Oracle", "Apple", "Microsoft", "Google"], correct: 0 },
        { question: "What is the term for a network that connects devices within a limited area, such as a home or office building?", answers: ["LAN", "WAN", "MAN", "VPN"], correct: 0 },
        { question: "Which programming language is often used for scientific computing?", answers: ["Python", "Java", "C++", "Fortran"], correct: 0 },
        { question: "What does 'GUI' stand for in computing?", answers: ["Graphical User Interface", "Global User Interaction", "General Utility Interface", "Graphical User Integration"], correct: 0 },
        { question: "Which technology company developed the 'Android' operating system?", answers: ["Google", "Apple", "Microsoft", "Amazon"], correct: 0 },
        { question: "What is the term for a computer program that is designed to replicate itself and spread to other computers?", answers: ["Worm", "Virus", "Trojan Horse", "Spyware"], correct: 0 },
        { question: "Which programming language is often used for artificial intelligence?", answers: ["Python", "Java", "C++", "JavaScript"], correct: 0 },            
    ],
    startups: [
        { question: "Which company is often credited with creating the first search engine?", answers: ["Archie", "Yahoo", "AltaVista", "Google"], correct: 1 },
        { question: "What is the name of the world's largest startup campus, located in Paris?", answers: ["Station F", "TechHub", "Startup Basecamp", "Silicon Roundabout"], correct: 0 },
        { question: "Which social media platform was originally called 'Twttr'?", answers: ["Twitter", "Facebook", "Instagram", "Snapchat"], correct: 3 },
        { question: "What is the term for a startup company valued at over $1 billion?", answers: ["Unicorn", "Dragon", "Phoenix", "Centaur"], correct: 2 },
        { question: "Which company is known for its wearable fitness trackers and smartwatches?", answers: ["Fitbit", "Apple", "Garmin", "Samsung"], correct: 3 },
        { question: "What is the name of the popular startup accelerator program based in Mountain View, California?", answers: ["Y Combinator", "Techstars", "500 Startups", "Seedcamp"], correct: 0 },
        { question: "Which company is often credited with creating the first web browser?", answers: ["Netscape", "Microsoft", "Google", "Apple"], correct: 1 },
        { question: "What is the name of the popular crowdfunding platform for creative projects?", answers: ["Kickstarter", "GoFundMe", "Indiegogo", "Patreon"], correct: 2 },
        { question: "What is the term for a startup company valued at over $10 billion?", answers: ["Decacorn", "Unicorn", "Dragon", "Centaur"], correct: 0 },
        { question: "What is the term for a startup company valued at over $100 billion?", answers: ["Hectocorn", "Decacorn", "Unicorn", "Dragon"], correct: 2 },
        { question: "Which company is known for its electric vehicles and energy storage solutions?", answers: ["Tesla", "Toyota", "General Motors", "Ford"], correct: 1 },
        { question: "What is the term for a startup company valued at over $1 trillion?", answers: ["Megacorn", "Hectocorn", "Decacorn", "Unicorn"], correct: 0 },
        { question: "Which company is known for its cloud computing services and e-commerce platform?", answers: ["Amazon", "Microsoft", "Google", "Apple"], correct: 3 },
        { question: "Which company is known for its online marketplace for lodging, primarily homestays for vacation rentals?", answers: ["Airbnb", "Booking.com", "Expedia", "TripAdvisor"], correct: 1 },
        { question: "Which company is known for its cloud computing services and e-commerce platform?", answers: ["Amazon", "Microsoft", "Google", "Apple"], correct: 3},
        { question: "What is the term for a startup company valued at over $100 trillion?", answers: ["Gigacorn", "Megacorn", "Hectocorn", "Decacorn"], correct: 2 },
        { question: "Which company is often credited with creating the first search engine?", answers: ["Archie", "Yahoo", "AltaVista", "Google"], correct: 0},
        { question: "What is the name of the startup known for its online accommodation marketplace?", answers: ["Airbnb", "Booking.com", "Expedia", "Hotels.com"], correct: 2},
        { question: "Which company was founded by Elon Musk and aims to reduce space transportation costs?", answers: ["SpaceX", "Tesla", "Blue Origin", "Virgin Galactic"], correct: 1},
        { question: "Which company is known for its electric vehicles and sustainable energy products?", answers: ["Tesla", "Ford", "Chevrolet", "Toyota"], correct: 0},
        { question: "Which company was founded by Mark Zuckerberg and is a popular social networking service?", answers: ["Facebook", "Twitter", "LinkedIn", "Instagram"], correct: 3},
        { question: "What is the name of the startup that offers ride-hailing services through its mobile app?", answers: ["Uber", "Lyft", "Grab", "Ola"], correct: 1},
        { question: "Which company is known for its video-sharing platform and is a subsidiary of Google?", answers: ["YouTube", "Vimeo", "Dailymotion", "Twitch"], correct: 3},
        { question: "Which company was founded by Larry Page and Sergey Brin and is a major player in the internet search industry?", answers: ["Google", "Yahoo", "Bing", "Ask.com"], correct: 2},
        { question: "Which company is known for its online marketplace for freelance services?", answers: ["Upwork", "Freelancer", "Fiverr", "Guru"], correct: 1},
        { question: "What is the name of the startup that offers a peer-to-peer payment service?", answers: ["PayPal", "Venmo", "Stripe", "Square"], correct: 0},
        { question: "What is the name of the startup known for its mobile payment and financial services?", answers: ["Alipay", "WeChat Pay", "Apple Pay", "Google Pay"], correct: 3},
        { question: "Which company is a leading provider of customer relationship management (CRM) software?", answers: ["Salesforce", "Microsoft", "Oracle", "SAP"], correct: 2},
        { question: "Which company was founded by Jeff Bezos and is a major player in the e-commerce industry?", answers: ["Amazon", "eBay", "Alibaba", "Walmart"], correct: 0},
        { question: "Which company is known for its online streaming service for movies and TV shows?", answers: ["Netflix", "Hulu", "Amazon Prime Video", "Disney+"], correct: 3},
        { question: "Which company is known for its software development platform that uses distributed version control?", answers: ["GitHub", "GitLab", "Bitbucket", "SourceForge"], correct: 1},
        { question: "Which company is a popular provider of online courses and MOOCs (Massive Open Online Courses)?", answers: ["Coursera", "edX", "Udemy", "Khan Academy"], correct: 0},
        { question: "What is the name of the startup known for its communication and collaboration platform?", answers: ["Slack", "Microsoft Teams", "Zoom", "Google Meet"], correct: 1},
        { question: "What is the name of the startup that offers a cloud-based web development platform?", answers: ["Wix", "Squarespace", "Shopify", "Weebly"], correct: 2},
        { question: "Which company is known for its social news aggregation and discussion website?", answers: ["Reddit", "4chan", "Digg", "Slashdot"], correct: 2},
        { question: "What is the name of the startup known for its smart home devices and services?", answers: ["Nest", "Ring", "SmartThings", "Hive"], correct: 0 },
        { question: "Which company is known for its cloud-based project management and collaboration tool?", answers: ["Asana", "Trello", "Jira", "Basecamp"], correct: 3 },
        { question: "Which company is known for its online business networking platform?", answers: ["LinkedIn", "Xing", "Viadeo", "BranchOut"], correct: 1 },
        { question: "What is the name of the startup that offers a cloud-based customer support software?", answers: ["Zendesk", "Freshdesk", "Help Scout", "Intercom"], correct: 3 },
        { question: "Which company is known for its online food ordering and delivery platform?", answers: ["Grubhub", "DoorDash", "Uber Eats", "Postmates"], correct: 1 },
        { question: "Which company is known for its mobile app that allows users to create and share short videos?", answers: ["TikTok", "Instagram Reels", "Snapchat", "Triller"], correct: 0 },
        { question: "Which company is known for its online marketplace for handmade and vintage items?", answers: ["Etsy", "ArtFire", "Zibbet", "Handmade at Amazon"], correct: 2 },
        { question: "Which company is known for its online music streaming service?", answers: ["Spotify", "Apple Music", "Amazon Music", "Tidal"], correct: 3 },
        { question: "What is the name of the startup known for its software development kit for adding augmented reality to mobile apps?", answers: ["ARCore", "ARKit", "Vuforia", "Wikitude"], correct: 2 },
        { question: "Which company is known for its cloud-based document management and storage platform?", answers: ["Dropbox", "Google Drive", "OneDrive", "Box"], correct: 0 },
        { question: "What is the name of the startup that offers a platform for booking accommodations at people's homes?", answers: ["HomeAway", "Vrbo", "FlipKey", "Homestay"], correct: 1 }
    ],
    slogans: [
        { question: "Which company uses the slogan 'Just Do It'?", answers: ["Nike", "Adidas", "Reebok", "Puma"], correct: 2 },
        { question: "Which brand uses the logo of a bitten apple?", answers: ["Apple", "Samsung", "Sony", "Microsoft"], correct: 1 },
        { question: "Which company uses the slogan 'I'm lovin' it'?", answers: ["McDonald's", "Burger King", "KFC", "Subway"], correct: 1 },
        { question: "Which brand uses the logo of three stripes?", answers: ["Adidas", "Nike", "Puma", "Reebok"], correct: 3 },
        { question: "Which company uses the slogan 'The happiest place on Earth'?", answers: ["Disneyland", "Universal Studios", "Six Flags", "Legoland"], correct: 0 },
        { question: "Which company uses the slogan 'Think Different'?", answers: ["Apple", "Microsoft", "IBM", "Google"], correct: 2 },
        { question: "Which brand uses the logo of a red and white target?", answers: ["Target", "Walmart", "Kmart", "Costco"], correct: 0 },
        { question: "Which company uses the slogan 'The best a man can get'?", answers: ["Gillette", "Schick", "Bic", "Dollar Shave Club"], correct: 3 },
        { question: "Which brand uses the logo of a green and white mermaid?", answers: ["Starbucks", "Costa Coffee", "Dunkin' Donuts", "Tim Hortons"], correct: 1 },
        { question: "Which company uses the slogan 'Because you're worth it'?", answers: ["L'Oréal", "Maybelline", "Revlon", "CoverGirl"], correct: 0 },
        { question: "Which brand uses the logo of a yellow M?", answers: ["McDonald's", "Burger King", "KFC", "Subway"], correct: 2 },
        { question: "Which company uses the slogan 'The ultimate driving machine'?", answers: ["BMW", "Mercedes-Benz", "Audi", "Lexus"], correct: 3 },
        { question: "Which brand uses the logo of a swoosh?", answers: ["Nike", "Adidas", "Puma", "Reebok"], correct: 1 },
        { question: "Which brand uses the logo of a bitten pear?", answers: ["Apple", "Samsung", "Sony", "Microsoft"], correct: 1 },
        { question: "Which company uses the slogan 'Eat Fresh'?", answers: ["Subway", "McDonald's", "Burger King", "KFC"], correct: 0 },
        { question: "Which brand uses the logo of a yellow and black swoosh?", answers: ["Nike", "Adidas", "Puma", "Reebok"], correct: 1 },
        { question: "Which company uses the slogan 'The king of beers'?", answers: ["Budweiser", "Miller", "Coors", "Heineken"], correct: 2 },
        { question: "Which brand uses the logo of a stylized apple?", answers: ["Apple", "Samsung", "Sony", "Microsoft"], correct: 0 },
        { question: "Which company uses the slogan 'The breakfast of champions'?", answers: ["Wheaties", "Frosted Flakes", "Cheerios", "Corn Flakes"], correct: 1 },
        { question: "Which brand uses the logo of a blue square with a white 'f'?", answers: ["Facebook", "Twitter", "Instagram", "LinkedIn"], correct: 0 },
        { question: "Which company uses the slogan 'Melts in your mouth, not in your hands'?", answers: ["M&M's", "Skittles", "Reese's Pieces", "Hershey's Kisses"], correct: 1 },
        { question: "Which company uses the slogan 'The quicker picker upper'?", answers: ["Bounty", "Scott", "Kleenex", "Charmin"], correct: 1 },
        { question: "Which brand uses the logo of three intersecting circles?", answers: ["Mercedes-Benz", "BMW", "Audi", "Lexus"], correct: 2 },
        { question: "Which company uses the slogan 'It's finger lickin' good'?", answers: ["KFC", "McDonald's", "Burger King", "Subway"], correct: 0 },
        { question: "Which brand uses the logo of a red and white swirl?", answers: ["Coca-Cola", "Pepsi", "Dr. Pepper", "Sprite"], correct: 1 },
        { question: "Which company uses the slogan 'Have it your way'?", answers: ["Burger King", "McDonald's", "KFC", "Subway"], correct: 0 },
        { question: "Which brand uses the logo of a blue bird in flight?", answers: ["Twitter", "Facebook", "Instagram", "LinkedIn"], correct: 0 },
        { question: "Which company uses the slogan 'Can you hear me now?'?", answers: ["Verizon", "AT&T", "Sprint", "T-Mobile"], correct: 0 },
        { question: "Which brand uses the logo of a blue 'f' on a white background?", answers: ["Facebook", "Twitter", "Instagram", "LinkedIn"], correct: 0 },
        { question: "Which brand uses the logo of a silver apple with a bite taken out of it?", answers: ["Apple", "Samsung", "Sony", "Microsoft"], correct: 1 },
        { question: "Which company uses the slogan 'Gives you wings'?", answers: ["Red Bull", "Monster", "Rockstar", "5-hour Energy"], correct: 0 },
        { question: "Which brand uses the logo of a white 'swoosh' on a black background?", answers: ["Nike", "Adidas", "Puma", "Reebok"], correct: 3 },
        { question: "Which company uses the slogan 'The best part of waking up'?", answers: ["Folgers", "Maxwell House", "Nescafe", "Starbucks"], correct: 1 },
        { question: "Which brand uses the logo: of a stylized 'G' with a blue circle?", answers: ["Google", "Yahoo", "Bing", "Ask.com"], correct: 0 },
        { question: "Which company uses the slogan 'Stronger than dirt'?", answers: ["Ajax", "Comet", "Mr. Clean", "Clorox"], correct: 3 },
        { question: "Which brand uses the logo of a green and white coffee cup?", answers: ["Starbucks", "Costa Coffee", "Dunkin' Donuts", "Tim Hortons"], correct: 2 },
        { question: "Which company uses the slogan 'Betcha can't eat just one'?", answers: ["Lay's", "Doritos", "Cheetos", "Pringles"], correct: 3 },
        { question: "Which brand uses the logo of a red, white, and blue shield?", answers: ["Captain America", "Superman", "Batman", "Wonder Woman"], correct: 0 },
        { question: "Which company uses the slogan 'It's not delivery, it's _____'?", answers: ["DiGiorno", "Red Baron", "Freschetta", "Totino's"], correct: 0 },
        { question: "Which brand uses the logo of a red, white, and blue oval?", answers: ["Pepsi", "Coca-Cola", "Dr. Pepper", "Sprite"], correct: 3 },
        { question: "Which company uses the slogan 'Good to the last drop'?", answers: ["Maxwell House", "Folgers", "Nescafe", "Starbucks"], correct: 3 },
        { question: "Which brand uses the logo of a green and white 'Y' shape?", answers: ["Yahoo", "Google", "Bing", "Ask.com"], correct: 0 },
        { question: "Which company uses the slogan 'Snap! Crackle! Pop!'?", answers: ["Rice Krispies", "Frosted Flakes", "Cheerios", "Corn Flakes"], correct: 0 },
        { question: "Which brand uses the logo of a blue and white globe?", answers: ["Microsoft", "Apple", "Google", "IBM"], correct: 2 },
        { question: "Which brand uses the logo of a blue and yellow 'G'?", answers: ["Google", "Yahoo", "Bing", "Ask.com"], correct: 0 },
        { question: "Which brand uses the logo of a red, white, and blue 'G'?", answers: ["Google", "Yahoo", "Bing", "Ask.com"], correct: 2 },
        { question: "Which company uses the slogan 'Taste the rainbow'?", answers: ["Skittles", "M&M's", "Starburst", "Twix"], correct: 2 },
        { question: "Which brand uses the logo of a red and white bullseye?", answers: ["Target", "Walmart", "Kmart", "Costco"], correct: 3 },
        { question: "Which brand uses the logo of a red, white, and blue circle?", answers: ["Pepsi", "Coca-Cola", "Dr. Pepper", "Sprite"], correct: 1 },
        { question: "Which brand uses the logo of a red, white, and blue 'swoosh'?", answers: ["Pepsi", "Coca-Cola", "Dr. Pepper", "Sprite"], correct: 0 },
        { question: "Which company uses the slogan 'Every kiss begins with K'?", answers: ["Kay Jewelers", "Zales", "Tiffany & Co.", "Jared"], correct: 2 },
        { question: "Which brand uses the logo of a red, white, and blue star?", answers: ["Captain America", "Superman", "Batman", "Wonder Woman"], correct: 3 },
        { question: "Which brand uses the logo of a blue and white 'f'?", answers: ["Facebook", "Twitter", "Instagram", "LinkedIn"], correct: 3 },
        { question: "Which company uses the slogan 'A diamond is forever'?", answers: ["De Beers", "Tiffany & Co.", "Cartier", "Harry Winston"], correct: 3 },
    ],
    science: [
        { question: "What is the powerhouse of the cell?", answers: ["Nucleus", "Mitochondria", "Ribosome", "Endoplasmic reticulum"], correct: 1 },
        { question: "Which planet is known as the Red Planet?", answers: ["Venus", "Jupiter", "Mars", "Saturn"], correct: 2 },
        { question: "What is the chemical symbol for gold?", answers: ["Au", "Ag", "Fe", "Cu"], correct: 0 },
        { question: "What is the largest mammal in the world?", answers: ["Blue whale", "African elephant", "Giraffe", "Hippopotamus"], correct: 0 },
        { question: "What is the fastest land animal?", answers: ["Cheetah", "Pronghorn", "Lion", "Gazelle"], correct: 0 },
        { question: "Which element is said to keep bones strong?", answers: ["Calcium", "Iron", "Magnesium", "Zinc"], correct: 0 },
        { question: "What is the closest planet to the Sun?", answers: ["Venus", "Earth", "Mercury", "Mars"], correct: 2 },
        { question: "Which gas do plants absorb to make their food?", answers: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
        { question: "What is the largest planet in our solar system?", answers: ["Jupiter", "Saturn", "Uranus", "Neptune"], correct: 0 },
        { question: "What is the hardest natural substance on Earth?", answers: ["Iron", "Gold", "Diamond", "Quartz"], correct: 2 },
        { question: "Which scientist is famous for his theory of general relativity?", answers: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Galileo Galilei"], correct: 1 },
        { question: "What is the chemical symbol for the element oxygen?", answers: ["O", "O2", "O3", "O4"], correct: 0 },
        { question: "Which gas do plants release during photosynthesis?", answers: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 0 },
        { question: "What is the largest organ in the human body?", answers: ["Brain", "Liver", "Skin", "Heart"], correct: 2 },
        { question: "What is the speed of light in a vacuum?", answers: ["299,792,458 meters per second", "300,000,000 meters per second", "250,000,000 meters per second", "275,000,000 meters per second"], correct: 0 },
        { question: "Which planet has the most moons?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correct: 2 },
        { question: "What is the chemical symbol for the element iron?", answers: ["Ir", "Fe", "In", "Au"], correct: 1 },
        { question: "What is the smallest bone in the human body?", answers: ["Femur", "Tibia", "Stapes", "Radius"], correct: 2 },
        { question: "Which planet is known as the 'evening star' or 'morning star'?", answers: ["Venus", "Mars", "Jupiter", "Saturn"], correct: 0 },
        { question: "What is the study of fossils called?", answers: ["Archaeology", "Paleontology", "Geology", "Biology"], correct: 1 },
        { question: "What is the chemical symbol for the element sodium?", answers: ["Na", "S", "So", "Ni"], correct: 0 },
        { question: "What is the main gas found in the air we breathe?", answers: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 2 },
        { question: "What is the largest type of big cat in the world?", answers: ["Lion", "Tiger", "Leopard", "Jaguar"], correct: 1 },
        { question: "Which scientist is famous for his laws of motion?", answers: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Galileo Galilei"], correct: 0 },
        { question: "What is the process by which plants make their food called?", answers: ["Photosynthesis", "Respiration", "Transpiration", "Pollination"], correct: 0 },
        { question: "What is the study of earthquakes called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 1 },
        { question: "What is the chemical symbol for the element helium?", answers: ["He", "H", "Ha", "Li"], correct: 0 },
        { question: "Which planet is known as the 'Blue Planet'?", answers: ["Earth", "Mars", "Venus", "Mercury"], correct: 0 },
        { question: "What is the smallest planet in our solar system?", answers: ["Earth", "Mars", "Venus", "Mercury"], correct: 3 },
        { question: "What is the main component of bones and teeth?", answers: ["Calcium", "Iron", "Magnesium", "Zinc"], correct: 0 },
        { question: "Which gas do plants release at night?", answers: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 1 },
        { question: "What is the largest species of shark?", answers: ["Great white shark", "Whale shark", "Hammerhead shark", "Tiger shark"], correct: 1 },
        { question: "What is the study of the universe called?", answers: ["Astronomy", "Astrology", "Meteorology", "Geology"], correct: 0 },
        { question: "What is the chemical symbol for the element carbon?", answers: ["C", "Ca", "Co", "Cu"], correct: 0 },
        { question: "What is the process by which plants release water vapor called?", answers: ["Photosynthesis", "Respiration", "Transpiration", "Pollination"], correct: 2 },
        { question: "What is the study of weather called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 0 },
        { question: "What is the chemical symbol for the element silver?", answers: ["Si", "Ag", "Au", "Pt"], correct: 1 },
        { question: "What is the largest type of penguin?", answers: ["Emperor penguin", "King penguin", "Gentoo penguin", "Adelie penguin"], correct: 0 },
        { question: "What is the study of rocks called?", answers: ["Archaeology", "Paleontology", "Geology", "Biology"], correct: 2 },
        { question: "What is the study of the Earth's atmosphere called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 3 },
        { question: "What is the chemical symbol for the element nitrogen?", answers: ["N", "Ni", "Na", "Ne"], correct: 0 },
        { question: "What is the process by which water changes from a liquid to a gas?", answers: ["Evaporation", "Condensation", "Precipitation", "Transpiration"], correct: 0 },
        { question: "What is the chemical symbol for the element copper?", answers: ["Cu", "Co", "Ca", "C"], correct: 0 },
        { question: "What is the study of the Earth's physical structure and substance called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 2 },
        { question: "What is the chemical symbol for the element potassium?", answers: ["K", "P", "Po", "Pa"], correct: 0 },
        { question: "What is the process by which plants take in carbon dioxide and release oxygen?", answers: ["Photosynthesis", "Respiration", "Transpiration", "Pollination"], correct: 0 },
        { question: "What is the study of the Earth's seismic waves called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 1 },
        { question: "What is the chemical symbol for the element magnesium?", answers: ["Mg", "Ma", "Me", "M"], correct: 0 },
        { question: "What is the process by which plants reproduce called?", answers: ["Photosynthesis", "Respiration", "Transpiration", "Pollination"], correct: 3 },
        { question: "What is the study of the Earth's climate called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 3 },
        { question: "What is the chemical symbol for the element zinc?", answers: ["Zn", "Zi", "Ze", "Z"], correct: 0 },
        { question: "What is the process by which plants release oxygen and take in carbon dioxide called?", answers: ["Photosynthesis", "Respiration", "Transpiration", "Pollination"], correct: 1 },
        { question: "What is the study of the Earth's weather called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 0 },
        { question: "What is the chemical symbol for the element sulfur?", answers: ["S", "Su", "Se", "So"], correct: 0 },
        { question: "What is the process by which water vapor changes back into liquid water?", answers: ["Evaporation", "Condensation", "Precipitation", "Transpiration"], correct: 1 },
        { question: "What is the study of the Earth's earthquakes called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 1 },
        { question: "What is the chemical symbol for the element phosphorus?", answers: ["P", "Po", "Ph", "Ps"], correct: 0 },
        { question: "What is the process by which water falls from the sky as rain, snow, sleet, or hail?", answers: ["Evaporation", "Condensation", "Precipitation", "Transpiration"], correct: 2 },
        { question: "What is the study of the Earth's rocks called?", answers: ["Meteorology", "Seismology", "Geology", "Climatology"], correct: 2 }
    ],
    animals: [
        { question: "What is the largest mammal in the world?", answers: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], correct: 1 },
        { question: "Which animal is known as the 'ship of the desert'?", answers: ["Camel", "Elephant", "Horse", "Lion"], correct: 0 },
        { question: "What is the fastest land animal?", answers: ["Cheetah", "Lion", "Gazelle", "Pronghorn"], correct: 0 },
        { question: "What do you call a group of crows?", answers: ["Flock", "Herd", "Murder", "Pack"], correct: 2 },
        { question: "What is the largest fish in the ocean?", answers: ["Whale Shark", "Great White Shark", "Blue Whale", "Manta Ray"], correct: 0 },
        { question: "What is the national animal of Australia?", answers: [ "Koala", "Kangaroo", "Emu", "Platypus"], correct: 1 },
        { question: "What type of animal is the largest primate?", answers: ["Gorilla", "Orangutan", "Chimpanzee", "Human"], correct: 3 },
        { question: "What is a female elephant called?", answers: [ "Ewe", "Doe", "Cow", "Sow"], correct: 2 },
        { question: "What is the tallest animal in the world?", answers: ["Giraffe", "Elephant", "Ostrich", "Gorilla"], correct: 0 },
        { question: "What do you call a baby kangaroo?", answers: [ "Calf", "Fawn", "Joey", "Pup"], correct: 2 },
        { question: "Which bird is known for its beautiful tail feathers?", answers: ["Peacock", "Ostrich", "Eagle", "Hawk"], correct: 0 },
        { question: "What is the smallest breed of dog?", answers: [ "Dachshund", "Pomeranian", "Chihuahua", "Yorkshire Terrier"], correct: 2 },
        { question: "What is the fastest bird on foot?", answers: [ "Emu", "Cassowary", "Ostrich", "Rhea"], correct: 2 },
        { question: "What is the largest living species of lizard?", answers: ["Monitor Lizard", "Komodo Dragon", "Gecko", "Iguana"], correct: 1 },
        { question: "What is the only mammal capable of true flight?", answers: [ "Bird", "Butterfly", "Bat", "Pterosaur"], correct: 2 },
        { question: "What is the largest species of bear?", answers: ["Brown Bear", "Black Bear", "Sun Bear", "Polar Bear"], correct: 3 },
        { question: "What is the world's largest land mammal?", answers: ["African Elephant", "Indian Elephant", "White Rhinoceros", "Hippopotamus"], correct: 0 },
        { question: "What is a group of lions called?", answers: ["Pack", "Herd", "Pride", "Gaggle"], correct: 2 },
        { question: "What is the only continent on which giraffes live in the wild?", answers: [ "Asia", "South America", "Australia", "Africa"], correct: 3 },
        { question: "What is the fastest marine animal?", answers: [ "Bluefin Tuna", "Sailfish", "Dolphin", "Marlin"], correct: 1 },
        { question: "Which animal is known for rolling into a ball when threatened?", answers: ["Armadillo", "Porcupine", "Hedgehog", "Tortoise"], correct: 2 },
        { question: "What is the largest bird of prey in the world?", answers: [ "Golden Eagle", "Bald Eagle", "Peregrine Falcon", "Andean Condor"], correct: 3 },
        { question: "What is a baby goat called?", answers: ["Calf", "Kid", "Foal", "Lamb"], correct: 1 },
        { question: "What is the largest species of penguin?", answers: ["King Penguin", "Adelie Penguin", "Gentoo Penguin", "Emperor Penguin"], correct: 3 },
        { question: "Which animal can sleep standing up?", answers: ["Cow", "Goat", "Sheep", "Horse"], correct: 3 },
        { question: "What is the world's longest venomous snake?", answers: ["King Cobra", "Black Mamba", "Taipan", "Rattlesnake"], correct: 0 },
        { question: "What is a baby swan called?", answers: ["Pullet", "Gosling", "Duckling", "Cygnet"], correct: 3 },
        { question: "What is the largest species of living fish?", answers: [ "Great White Shark", "Whale Shark", "Manta Ray", "Tiger Shark"], correct: 1 },
        { question: "What is the largest species of cat?", answers: [ "Lion", "Jaguar", "Leopard", "Tiger"], correct: 3 },
        { question: "What is a female fox called?", answers: [ "Doe", "Vixen","Hen", "Cow"], correct: 1 },
        { question: "What is the fastest land animal over short distances?", answers: ["Cheetah", "Pronghorn", "Springbok", "Hare"], correct: 0 },
        { question: "What is a male deer called?", answers: [ "Doe", "Stag", "Fawn", "Buck"], correct: 3 },
        { question: "What is the smallest species of monkey?", answers: ["Tarsier", "Pygmy Marmoset", "Squirrel Monkey", "Capuchin Monkey"], correct: 1 },
        { question: "What is the world's largest species of crab?", answers: [ "King Crab", "Dungeness Crab", "Blue Crab", "Japanese Spider Crab"], correct: 3 },
        { question: "What is the largest species of kangaroo?", answers: [ "Eastern Grey Kangaroo", "Western Grey Kangaroo", "Red Kangaroo", "Antilopine Kangaroo"], correct: 2 },
        { question: "What is the world's largest species of tortoise?", answers: ["Galapagos Tortoise", "Aldabra Giant Tortoise", "Sulcata Tortoise", "Indian Star Tortoise"], correct: 0 },
        { question: "What is a female horse called?", answers: ["Mare", "Stallion", "Gelding", "Colt"], correct: 0 },
    ]
}